package model;
// Generated 02-nov-2016 17:00:05 by Hibernate Tools 4.3.1



/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String mapa;

    public Distrito() {
    }

	
    public Distrito(int codigo) {
        this.codigo = codigo;
    }
    public Distrito(int codigo, String nombre, String mapa) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.mapa = mapa;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMapa() {
        return this.mapa;
    }
    
    public void setMapa(String mapa) {
        this.mapa = mapa;
    }




}


